apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.bastian-somon.fr/laponie-gouv-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: laponie-gouv-secret
      imagePullSecrets:
        - name: registry-creds
