apiVersion: v1
kind: Service
metadata:
  name: laponie-gouv-backend # Sets service name
  labels:
    app: laponie-gouv-backend # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 8080
      name: http
  selector:
    app: spring
