version: "3.9"

services:

  # Service for the database
  laponie-gouv-db:
    container_name: laponie-gouv-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laponie-gouv
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  laponie-gouv-mailhog:
    container_name: laponie-gouv-mailhog
    image: mailhog/mailhog
    ports:
      - "8026:8025"
      - "1026:1025"
    environment:
      MH_STORAGE: maildir
    volumes:
      - smtp_data:/maildir

volumes:
  db-data:
  smtp_data:
