kind: PersistentVolume
apiVersion: v1
metadata:
  name: laponie-gouv-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nas/kube
    server: 86.247.170.156
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: laponie-gouv-pvc # Sets name of PV
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
