kind: PersistentVolume
apiVersion: v1
metadata:
  name: laponie-gouv-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bastian-somon
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: laponie-gouv-pvc # Sets name of PV
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 1Gi # Sets volume size
