name: LaponieGouv CD

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file laponie-gouv-api/pom.xml

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr --username ${{ secrets.REGISTRY_USER }} --password-stdin 
          docker build -t registry.bastian-somon.fr/laponie-gouv-backend:latest laponie-gouv-api
          docker push registry.bastian-somon.fr/laponie-gouv-backend:latest

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr --username ${{ secrets.REGISTRY_USER }} --password-stdin 
          docker build -t registry.bastian-somon.fr/laponie-gouv-frontend:latest laponie-gouv-client
          docker push registry.bastian-somon.fr/laponie-gouv-frontend:latest

  deploy-infra:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: davi020/kubernetes-action@V1
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -k infra/application

  rollout-infra:
    needs: [deploy-infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: davi020/kubernetes-action@V1

        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment spring -n laponie-gouv

      - name: Trigger frontend rollout
        uses: davi020/kubernetes-action@V1

        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment nginx -n laponie-gouv
