name: LaponieGouv CD

on:
  push:
    branches:
      - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Action for GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check arch
        run: uname -a

      - name: Build with Maven
#        run: mvn -Pnative clean native:compile --file laponie-gouv-api/pom.xml
        run: mvn -B package --file laponie-gouv-api/pom.xml

      - name: Login and push to container registry
        run: |
          ls -lart laponie-gouv-api/target
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr --username ${{ secrets.REGISTRY_USER }} --password-stdin 
          docker build -t registry.bastian-somon.fr/laponie-gouv-backend:latest laponie-gouv-api -f laponie-gouv-api/Dockerfile.jvm
          docker push registry.bastian-somon.fr/laponie-gouv-backend:latest

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr --username ${{ secrets.REGISTRY_USER }} --password-stdin 
          docker build -t registry.bastian-somon.fr/laponie-gouv-frontend:latest laponie-gouv-client
          docker push registry.bastian-somon.fr/laponie-gouv-frontend:latest

  deploy-infra:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: fno/kubernetes-action-no-aws@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -k infra/application

  rollout-infra:
    needs: [deploy-infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Kubernetes Action with Python 2.x fixes
        uses: fno/kubernetes-action-no-aws@master

        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment spring -n laponie-gouv

      - name: Trigger frontend rollout
        uses: fno/kubernetes-action-no-aws@master

        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment nginx -n laponie-gouv
